export * from 'components/404'
export * from 'container/dashboard'
export * from 'container/login'
export * from 'container/update/Banners'
export * from 'container/update/Card'
export * from 'container/update/Location'
export * from 'container/update/Notifications'
export * from 'container/update/Pqr'
export * from 'container/update/PromoBannerDashboard'
export * from 'container/update/PromosBanner'
export * from 'container/update/Stores'
export * from 'container/update/categoria-tienda'

