import { Activity } from 'container/Activity'
import { LocationName } from 'hooks/useLocationName'
import Head from 'next/head'
export default function Home () {
  return (
    <div >
      <Head>
        <title>{process.env.NEXT_NAME_APP}</title>
        <meta content='Generated by create next app' name='description' />
        <link href='/favicon.ico' rel='icon' />
      </Head>
      <LocationName />
      <Activity />
    </div>
  )
}
