import withSession from 'apollo/session'
import Head from 'next/head'
import { Banners } from 'container/update/Banners'
export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta content='Generated by create next app' name='description' />
        <link href='/favicon.ico' rel='icon' />
      </Head>
      <Banners />
    </div>
  )
}
export const getServerSideProps = withSession(async function ({ req, res }) {
  const user = req?.session?.get('user')
  if (!user) {
    res.setHeader('location', '/')
    res.statusCode = 302
    res.end()
    return { props: {} }
  }
  if (!req.cookies[process.env.SESSION_NAME]) return { redirect: { destination: '/' } }
  
  return {
    props: {}
  }
}
)
  