import { Login } from 'container/login'
import Head from 'next/head'
import axios from 'axios'
import { EmptyLayout } from './_app'
export default function Home() {

  const onChange = async (formData) => {
    const config = {
      headers: { 'content-type': 'multipart/form-data' },
      onUploadProgress: (event) => {
        console.log(`Current progress:`, Math.round((event.loaded * 100) / event.total))
      }
    }
    const response = await axios.post('/api/uploads', formData, config)
    console.log('response', response.data)
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta content='Generated by create next app' name='description' />
        <link href='/favicon.ico' rel='icon' />
      </Head>
      <Login
        label='Upload Single File'
        onChange={onChange}
        uploadFileName='theFiles'
      />
    </div>
  )
}

Home.Layout = EmptyLayout
